sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: content
        field:
          collapse: false
          always_show_set_button: false
          previews: true
          smart_typography: false
          buttons:
            - h2
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - quote
            - anchor
            - image
            - h4
            - underline
            - alignleft
          container: assets
          save_html: false
          inline: false
          toolbar_mode: fixed
          link_noopener: true
          link_noreferrer: true
          target_blank: true
          reading_time: false
          fullscreen: true
          allow_source: true
          enable_input_rules: true
          enable_paste_rules: true
          antlers: false
          remove_empty_nodes: false
          display: Content
          type: bard
          icon: bard
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
          sets:
            video_embed:
              display: 'Video Embed'
              fields:
                -
                  handle: video
                  field:
                    display: Video
                    type: video
                    icon: video
                    listable: hidden
                    instructions_position: above
                    visibility: visible
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: parent
        field:
          type: entries
          collections:
            - recipes
          max_items: 1
          listable: false
          localizable: true
      -
        handle: image
        field:
          mode: list
          container: assets
          restrict: false
          allow_uploads: true
          show_filename: true
          max_files: 1
          display: Image
          type: assets
          icon: assets
          listable: hidden
          instructions_position: above
          visibility: visible
          validate:
            - required
title: Recipe
